# Generated by Django 6.0.1 on 2026-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
